### ISSUE TITLE
Word lists not saved

### ISSUE THREAD

**Issue by GiraffeCubed** [qwerasd205/qwerasd205.github.io#1]
When adding words to the list in plugin settings, upon hitting `Apply` the words are only saved until you next restart your client, at which point they're reset. No config file is created in order to save the words.

Would also be nice if the notifications could pop up an unread count in the serrver they were triggered in, and/or highlight the comment in some way that contained the word(s).

**Comment by qwerasd205** [comment]
Yes, the first draft of the plugin was very hastily done, for now toggling the plugin off and on will save the words list.
