### ISSUE TITLE
Extended Context Menu Broken

### ISSUE THREAD

**Issue by mutageneral** [qwerasd205/qwerasd205.github.io#10]
Extended Context Menu cashes on starting the plugin`
load() could not be fired.
Cannot read property 'contextMenu' of undefined`

**Comment by qwerasd205** [comment]
This plugin is discontinued. All its features have been superseded by official Discord features.

**Comment by mutageneral** [comment]
ah okay sorry, you should get it removed from the Plugin Repo then but idk how that works...
