### ISSUE TITLE
I NEED THIS

### ISSUE THREAD

**Issue by Toskan4134** [qwerasd205/qwerasd205.github.io#13]
PLEASE, I NEED THIS PLUGIN SO HARD, UPDATE EDIT UPLOADS PLEASEEEE

**Comment by qwerasd205** [comment]
Maybe in a month or so when I start taking medication for my ADHD I'll get around to it. Until then just use photoshop or GIMP or something. Sorry for the inconvenience.

**Comment by Toskan4134** [comment]
Thaaaanksssss good luck with adhd. Get better soon!!
