### ISSUE TITLE
Dyslexia - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by LunarGhost** [qwerasd205/qwerasd205.github.io#6]
It is not working for me. Its not even showing up in the themes tab on discord.

**Comment by qwerasd205** [comment]
Do not use Discord source. Use the "Official Theme List" channel in [the BetterDiscord server](https://discord.gg/2HScm8j). For a download for the Dyslexia theme you can use this page, though: https://qwerasd205.github.io/Dyslexia
