### ISSUE TITLE
"load() could not be fired." error when starting Discord

### ISSUE THREAD

**Issue by derMiepz** [qwerasd205/qwerasd205.github.io#7]
When starting Discord, this window pops up 
![image](https://user-images.githubusercontent.com/45405525/89376428-fe49d200-d6ef-11ea-8df0-ae32009a1c20.png)
The blue text seems like a link of some sort but cannot be clicked. When right clicking and copying, it copies `https://discordapp.com/channels/@me` into the clipboard.

Best regards
~Fabi

**Comment by qwerasd205** [comment]
I am aware that this plugin is broken. I do not plan on fixing it, as most of the things it was useful for have been superseded by base discord features.

**Comment by derMiepz** [comment]
Alrighty, thanks for the quick reply though!
