### ISSUE TITLE
EditUploads plugin not working

### ISSUE THREAD

**Issue by ashergz** [qwerasd205/qwerasd205.github.io#9]
What the title says. Latest discord update seems to have broken plugin functionality, and now you no longer see an edit button when uploading images.

Please look into this and update plugin.

**Comment by qwerasd205** [comment]
Cannot reproduce. What distribution of Discord are you using? Stable, PTB, or Canary?

**Comment by ashergz** [comment]
Sorry, looks like it was a problem on my end. I checked again and it is working now.
